### ISSUE TITLE
[BUG] Publish API not working with Bot Chat has no file upload.  errorInfo:Invalid type for parameter knowledgeBaseId

### ISSUE THREAD

**Issue by RichardLeeY** [aws-samples/bedrock-claude-chat#598]
## Describe the bug
When I create a bot only have prompts and **no file uploaded**.Then I share the bot and create a publish api for this bot.
After creating conversation, I can't get conversation info by conversation_id with API.

## To Reproduce

1. Go to  'Bot Console'
2. Click on 'Create new Bot',  fufill the forms and do not upload file .
3. Click on 'Create', 
4. After "Completed Sync",  Create Published API by 'API Publish Setting'
5. Create a Conversation with 'Post conversion API'
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/8f144e9a-20ce-43c5-8011-ead920ad9cf3">
6. Now get Conversation info by conversationid
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/2a3500ac-3c76-4264-a056-12cbde6048cd">
7. Check from the lambda function 'ApiPublishmentStack01JCW0-SqsConsumeHandler0CD11EA-KSfW8R21fUVK' cloudwatch log

```
Invalid type for parameter knowledgeBaseId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Traceback (most recent call last):
  File "/var/task/app/sqs_consumer.py", line 27, in handler
    chat_result = chat(user_id=user_id, chat_input=chat_input)
  File "/var/task/app/usecases/chat.py", line 297, in chat
    search_results = search_related_docs(bot=bot, query=query)
  File "/var/task/app/vector_search.py", line 126, in search_related_docs
    return _bedrock_knowledge_base_search(bot, query)
  File "/var/task/app/vector_search.py", line 94, in _bedrock_knowledge_base_search
    response = agent_client.retrieve(
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
```
So to conclude, I think the publish api feature should consider to support bot that without file uploaded that means no knowledgebase created.

**Comment by statefb** [comment]
Could you create another bot with the same configuration and try it again?

**Comment by RichardLeeY** [comment]
You mean it's fixed now? Do I need to pull the code now?
