### ISSUE TITLE
Input is too long for requested model

### ISSUE THREAD

**Issue by severity1** [aws-samples/bedrock-claude-chat#95]
Getting this error on one of my chats.

[ERROR] EventStreamError: An error occurred (validationException) when calling the InvokeModelWithResponseStream operation: Input is too long for requested model.
Traceback (most recent call last):
  File "/var/task/app/websocket.py", line 84, in handler
    for chunk in generate_chunk(stream):
  File "/var/task/app/websocket.py", line 23, in generate_chunk
    for event in stream:
  File "/var/lang/lib/python3.11/site-packages/botocore/eventstream.py", line 603, in __iter__
    parsed_event = self._parse_event(event)
  File "/var/lang/lib/python3.11/site-packages/botocore/eventstream.py", line 619, in _parse_event
    raise EventStreamError(parsed_response, self._operation_name)

**Comment by statefb** [comment]
Please try the latest version. If you still have the same issue, please create another issue with more information such as reproduction step. thank you
